
variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  MYSQL_ROOT_PASSWORD: keanu
  MYSQL_DATABASE: keanu_test
  DATABASE_TEST_URL: mysql+pymysql://root:keanu@mysql-keanu/keanu_test

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

test_loader:
  image: $CONTAINER_IMAGE
  stage: test
  services:
    - name: mysql:5.7
      alias: mysql-keanu
      command: ["--character-set-server=utf8", "--collation-server=utf8_general_ci"]
  rules:
   - if: $CI_COMMIT_TAG == null
     when: always
  before_script:
    - apt-get update && apt-get install -y default-mysql-client wait-for-it
  script:
    - wait-for-it -t 60 mysql-keanu:3306
    - mysql -h mysql-keanu -u root -pkeanu -e "CREATE DATABASE civicrm_tiny"
    - mysql -h mysql-keanu -u root -pkeanu civicrm_tiny < tests/civicrm/civicrm_tiny.sql
    - python3 /app/keanu.py test tests/civicrm/test-config.yaml tests/civicrm

build:
  image: docker:18-git
  services:
    - docker:18-dind
  stage: build
  rules:
   - if: $CI_COMMIT_TAG == null
     when: always
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE

release:
  stage: build
  rules:
   - if: $CI_COMMIT_TAG != null
     when: always
  script:
   - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
   - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG