#!/bin/bash

set -e
set -u

HOSTNAME=mysql.docker
IP=172.19.0.10
VOL=/tmp/keanu-test-mysql

getent hosts $HOSTNAME > /dev/null
if [ $? -gt 0 ]; then
    echo "Add this line to /etc/hosts"
    echo "$IP		$HOSTNAME"
    exit 1
fi

mkdir $VOL || true
docker run -d --hostname HOSTNAME \
       --name mysqld \
       -v $VOL:/var/lib/mysql  \
       --net proca --ip $IP \
       -e MYSQL_ROOT_PASSWORD= \
       -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
       mysql:5.7 \
       --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


