-- MySQL Script generated by MySQL Workbench
-- śro, 28 sie 2019, 17:08:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ceval
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ceval
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ceval` DEFAULT CHARACTER SET utf8 ;
USE `ceval` ;

-- -----------------------------------------------------
-- Table `ceval`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceval`.`contacts` ;

CREATE TABLE IF NOT EXISTS `ceval`.`contacts` (
  `id` INT NOT NULL,
  `email` VARCHAR(254) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceval`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceval`.`table1` ;

CREATE TABLE IF NOT EXISTS `ceval`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
