-- MySQL Script generated by MySQL Workbench
-- pon, 18 maj 2020, 20:11:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema keanu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema keanu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `keanu` ;
USE `keanu` ;

-- -----------------------------------------------------
-- Table `keanu`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`contact` ;

CREATE TABLE IF NOT EXISTS `keanu`.`contact` (
  `id` INT NOT NULL,
  `email_domain` VARCHAR(254) NULL COMMENT 'The part after the @ in the primary email address of the contact',
  `created_at` DATETIME NOT NULL COMMENT 'When the contact was added to our database',
  `postal_code` VARCHAR(10) NULL,
  `country` VARCHAR(64) NULL COMMENT 'The 2-letter country code of the contact.\nWhat this country represents is up to the contact (place of birth, place of living, etc).',
  `preferred_language` VARCHAR(5) NULL COMMENT 'The language used to communicate with the contact, in locale format (xx_YY)',
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `created_at_idx` (`created_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`campaign` ;

CREATE TABLE IF NOT EXISTS `keanu`.`campaign` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL COMMENT 'The internal name of the campaign',
  `started_at` DATETIME NOT NULL COMMENT 'When the campaign was launched',
  `ended_at` DATETIME NULL COMMENT 'When the campaign was closed',
  `campaign_type` ENUM('youmove', 'eci', 'wemove', 'trial') NOT NULL COMMENT 'One of the following:\n - wemove: a \"regular\" campaign run by the organisation\n - youmove: a campaign initiated by a citizen or organisation on the Youmove platform\n - eci: European Citizen Initiative\n - trial: a campaign run the organisation to assess its potential success',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_campaign') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC))
COMMENT = 'In the context of analytics, a campaign is a \"project\" with a political and/or organisational goal. It is the primary concept used to focus data analysis to a specific area or goal. \nN.B.: It may be different from what your action tool or CRM may refer to as campaign, which is rather a technical definition and is closer to the analytics concept of action page.';


-- -----------------------------------------------------
-- Table `keanu`.`topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`topic` ;

CREATE TABLE IF NOT EXISTS `keanu`.`topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `keanu`.`campaign_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`campaign_topic` ;

CREATE TABLE IF NOT EXISTS `keanu`.`campaign_topic` (
  `campaign_id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  INDEX `fk_campaign_topics_campaigns1_idx` (`campaign_id` ASC),
  INDEX `fk_campaign_topics_topics1_idx` (`topic_id` ASC),
  UNIQUE INDEX `campaign_tagged_once` (`topic_id` ASC, `campaign_id` ASC),
  CONSTRAINT `fk_campaign_topics_campaigns1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `keanu`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaign_topics_topics1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `keanu`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`source` ;

CREATE TABLE IF NOT EXISTS `keanu`.`source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(45) NOT NULL,
  `medium` VARCHAR(45) NOT NULL,
  `campaign` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(2) NULL,
  `description` VARCHAR(64) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_codes` (`source` ASC, `medium` ASC, `campaign` ASC))
ENGINE = InnoDB
COMMENT = 'A source is a set of so-called utm parameters that can be used to identify how someone got exposed to a link. It is a major mechanism of action attribution.\n';


-- -----------------------------------------------------
-- Table `keanu`.`action_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`action_page` ;

CREATE TABLE IF NOT EXISTS `keanu`.`action_page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campaign_id` INT NOT NULL,
  `action_type` ENUM('sign', 'email', 'tweet', 'facebook', 'call', 'share', 'donate', 'consent') NOT NULL COMMENT 'Kind of engagement that users can do on the action page.\nThe type consent is listed here for technical reasons, consents are not considered as actions and are recorded in the consent table.',
  `language` VARCHAR(5) NULL COMMENT 'Language of the page in locale format (xx_YY where xx is language code and YY is country code)',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_campaign') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actions_campaigns1_idx` (`campaign_id` ASC),
  UNIQUE INDEX `external_id_system_action_type_idx` (`external_system` ASC, `external_id` ASC, `action_type` ASC),
  INDEX `action_type_idx` (`action_type` ASC),
  CONSTRAINT `fk_actions_campaigns1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `keanu`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'An action page is a place (such as a web page or a form) written in a given language where we want people to perform actions of a given type. An action page is always associated to a campaign.';


-- -----------------------------------------------------
-- Table `keanu`.`action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`action` ;

CREATE TABLE IF NOT EXISTS `keanu`.`action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_id` INT NOT NULL COMMENT 'Contact who did the action',
  `created_at` DATETIME NOT NULL COMMENT 'When the contact did the action',
  `source_id` INT NULL COMMENT 'The utm parameters that led to this action',
  `action_page_id` INT NOT NULL COMMENT 'The action page where the action was done.\nAttributes a type, language and campaign to the action.',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_contribution_recur', 'civicrm_contribution', 'civicrm_activity') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actions_contacts1_idx` (`contact_id` ASC),
  INDEX `fk_actions_sources1_idx` (`source_id` ASC),
  INDEX `fk_actions_action_pages1_idx` (`action_page_id` ASC),
  INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_contact_actions_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_actions_sources1`
    FOREIGN KEY (`source_id`)
    REFERENCES `keanu`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_actions_action_page1`
    FOREIGN KEY (`action_page_id`)
    REFERENCES `keanu`.`action_page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'An action is what a single person does on an action page, a specific engagement act performed by a person. It is therefore the link between a contact and an action page.';


-- -----------------------------------------------------
-- Table `keanu`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`tag` ;

CREATE TABLE IF NOT EXISTS `keanu`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `external_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `external_id_idx` (`external_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`contact_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`contact_tag` ;

CREATE TABLE IF NOT EXISTS `keanu`.`contact_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `tag_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `joined` DATETIME NOT NULL,
  `left` DATETIME NOT NULL,
  `trigger_action_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_ct_segments1_idx` (`tag_id` ASC),
  INDEX `fk_id_ct_contacts1_idx` (`contact_id` ASC),
  INDEX `fk_id_ct_contact_actions1_idx` (`trigger_action_id` ASC),
  INDEX `joined_idx` (`joined` ASC),
  INDEX `left_idx` (`left` ASC),
  CONSTRAINT `fk_id_ct_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `keanu`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ct_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ct_contact_action1`
    FOREIGN KEY (`trigger_action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`broadcast_test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`broadcast_test` ;

CREATE TABLE IF NOT EXISTS `keanu`.`broadcast_test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT 'Internal name of the test',
  `created_at` DATETIME NOT NULL COMMENT 'When the test was created in database',
  `sent_at` DATETIME NULL COMMENT 'When the sending of the test started',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_abtest') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `sent_at_idx` (`sent_at` ASC))
ENGINE = InnoDB
COMMENT = 'A broadcast test is a set of broadcasts sent at the same time but to different people, meant to be compared to each other to identify the one that performs best. It is also known as an A/B test or A/B/n test.';


-- -----------------------------------------------------
-- Table `keanu`.`broadcast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`broadcast` ;

CREATE TABLE IF NOT EXISTS `keanu`.`broadcast` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT 'Internal name of the broadcast',
  `broadcast_type` ENUM('email', 'fb_ad') NOT NULL COMMENT 'Broadcast medium',
  `ask_type` ENUM('sign', 'email', 'tweet', 'facebook', 'call', 'share', 'donate', 'noop_read', 'noop_watch') NOT NULL COMMENT 'The type of action that the recipients is asked to do.\nShould match the action_type of action_page.',
  `language` VARCHAR(5) NOT NULL COMMENT 'The language in which the broadcast was written, in locale format (xx_YY).',
  `sent_at` DATETIME NOT NULL COMMENT 'When the sending of the broadcast started',
  `broadcast_test_id` INT NULL,
  `campaign_id` INT NOT NULL DEFAULT 0,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing') NULL,
  PRIMARY KEY (`id`),
  INDEX `broadcast_type_idx` (`broadcast_type` ASC),
  INDEX `ask_type_idx` (`ask_type` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_broadcast_test_idx` (`broadcast_test_id` ASC),
  INDEX `fk_broadcast_campaign_idx` (`campaign_id` ASC),
  CONSTRAINT `fk_broadcast_test`
    FOREIGN KEY (`broadcast_test_id`)
    REFERENCES `keanu`.`broadcast_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_broadcast_campaign`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `keanu`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A broadcast is a way to direct people to action pages, using group / mass communication.';


-- -----------------------------------------------------
-- Table `keanu`.`broadcast_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`broadcast_link` ;

CREATE TABLE IF NOT EXISTS `keanu`.`broadcast_link` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` TEXT NOT NULL COMMENT 'Complete target URL of the link, including utm parameters.\nThis is not the URL of the click tracking system.',
  `broadcast_id` INT NOT NULL,
  `source_id` INT NOT NULL COMMENT 'utm parameters that were used in the URL',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_trackable_url') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_broadcast_link_broadcast_idx` (`broadcast_id` ASC),
  INDEX `fk_broadcast_link_source_idx` (`source_id` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_broadcast_link_broadcast`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_broadcast_link_source`
    FOREIGN KEY (`source_id`)
    REFERENCES `keanu`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A broadcast link is a web link found in the content of a broadcast.\nIt is associated to the source that matches the utm parameters used in the link, which can be used to attribute actions to a broadcast.';


-- -----------------------------------------------------
-- Table `keanu`.`click`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`click` ;

CREATE TABLE IF NOT EXISTS `keanu`.`click` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `mailing_link_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_event_trackable_url_open') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mailing_links_id1_idx` (`mailing_link_id` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_click_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_mailing_links_id1`
    FOREIGN KEY (`mailing_link_id`)
    REFERENCES `keanu`.`broadcast_link` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_click_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A click is the act of opening a link in a broadcast.\nThe information is obtained by using an intermediary system that identifies and redirects recipients to the destination URL after capturing each click event.';


-- -----------------------------------------------------
-- Table `keanu`.`segmentation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`segmentation` ;

CREATE TABLE IF NOT EXISTS `keanu`.`segmentation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_group', 'civicrm_option_group') NULL,
  PRIMARY KEY (`id`),
  INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC))
ENGINE = InnoDB
COMMENT = 'A segmentation is a way split a group of people into different segments (sub-groups).\nThis split is a partition: each person of the base group is attributed to exactly one segment (everyone is in a segment, no-one is in more than one segment).';


-- -----------------------------------------------------
-- Table `keanu`.`segment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`segment` ;

CREATE TABLE IF NOT EXISTS `keanu`.`segment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `segmentation_id` INT NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_group', 'civicrm_option_value', 'civicrm_country') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_segment_segmentation1_idx` (`segmentation_id` ASC),
  INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_segment_segmentation1`
    FOREIGN KEY (`segmentation_id`)
    REFERENCES `keanu`.`segmentation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A segment is a sub-group of a segmentation.';


-- -----------------------------------------------------
-- Table `keanu`.`contact_segment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`contact_segment` ;

CREATE TABLE IF NOT EXISTS `keanu`.`contact_segment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `segmentation_id` INT NOT NULL COMMENT 'this is necessary to have one segment per segmentation enforced for a contact.',
  `segment_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `joined_at` DATETIME NOT NULL COMMENT 'When the contact joined the segment.\nIf the contact was in the segment several times, there are several records.\n',
  `left_at` DATETIME NULL COMMENT 'When the contact left the segment, or NULL if the contact is still in the segment.\nIt is equal to the joined_at column for the next segment within this segmentation.',
  `trigger_action_id` INT NULL COMMENT 'If applicable, the id of the action that made the contact join the segment',
  PRIMARY KEY (`id`),
  INDEX `fk_contact_segment_map_contact_segment1_idx` (`segmentation_id` ASC),
  INDEX `fk_contact_segment_map_contacts1_idx` (`contact_id` ASC),
  INDEX `fk_contact_segment_map_contact_action1_idx` (`trigger_action_id` ASC),
  INDEX `fk_contact_segmentation_segment1_idx` (`segment_id` ASC),
  UNIQUE INDEX `one_segment_in_segmentation_at_a_time` (`segmentation_id` ASC, `contact_id` ASC, `joined_at` ASC),
  INDEX `joined_at_idx` (`joined_at` ASC),
  INDEX `left_at_idx` (`left_at` ASC),
  CONSTRAINT `fk_contact_segment_map_contact_segment1`
    FOREIGN KEY (`segmentation_id`)
    REFERENCES `keanu`.`segmentation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_segment_map_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_segment_map_contact_action1`
    FOREIGN KEY (`trigger_action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_segmentation_segment1`
    FOREIGN KEY (`segment_id`)
    REFERENCES `keanu`.`segment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A contact_segment record is a link between a person and a segment.';


-- -----------------------------------------------------
-- Table `keanu`.`donation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`donation` ;

CREATE TABLE IF NOT EXISTS `keanu`.`donation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_id` INT NOT NULL,
  `frequency_unit` ENUM('one-off', 'month') NOT NULL COMMENT 'one-off for a one-off donation, month for a recurring donation',
  `frequency_interval` SMALLINT NOT NULL DEFAULT 1,
  `amount` DECIMAL(10,2) NOT NULL COMMENT 'Amount of the donation converted into the organisation currency',
  `original_currency` VARCHAR(3) NOT NULL COMMENT 'The currency in which the donation is made',
  `original_amount` DECIMAL(16,2) NOT NULL COMMENT 'The amount of the donation in the original currency',
  `payment_method` ENUM('sepa', 'paypal', 'card', 'bank_transfer') NOT NULL COMMENT 'How the donation is paid.\nSepa (aka direct debit) is a transfer initiated by the organisation on request of the donor, while a bank_transfer is a transfer initated by the donor.',
  `started_at` DATETIME NOT NULL COMMENT 'For a recurring donation, when the donation started.\nFor a one-off donation, when it is received.',
  `ended_at` DATETIME NULL COMMENT 'For a recurring donation, when it stopped.\nFor a one-off donation, undefined.',
  `total_amount` DECIMAL(16,2) NOT NULL COMMENT 'Amount sum of all successful payments',
  `payment_count` INT NOT NULL DEFAULT 0 COMMENT 'Number of successful payments for this donation',
  `fail_count` INT NOT NULL DEFAULT 0 COMMENT 'Number of failed payments for this donation',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_contribution_recur', 'civicrm_contribution') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_donation_contact_action1_idx` (`action_id` ASC),
  UNIQUE INDEX `external_id_external_system_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_donation_action10`
    FOREIGN KEY (`action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A donation a type of action: it is the intent from a person to give money to the organisation, either once or periodically. The intent may or may not be eventually fulfilled.\nN.B.: The campaign associated to a donation (through action and action page) is not the campaign for which the money should be used, but rather the campaign that led the person to donate.';


-- -----------------------------------------------------
-- Table `keanu`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`payment` ;

CREATE TABLE IF NOT EXISTS `keanu`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `donation_id` INT NOT NULL,
  `receive_date` DATETIME NOT NULL COMMENT 'When the payment was attempted',
  `status` ENUM('success', 'fail', 'cancel') NOT NULL COMMENT 'One of:\n - success: the payment was processed\n - fail: the payment could not be processed\n - cancel: the payment was processed but the donor requested to take it back',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_contribution_recur', 'civicrm_contribution') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_donation1_idx` (`donation_id` ASC),
  UNIQUE INDEX `external_id_external_system_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_payment_donation1`
    FOREIGN KEY (`donation_id`)
    REFERENCES `keanu`.`donation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A payment is an attempt (successful or failed) to fulfill a donation.';


-- -----------------------------------------------------
-- Table `keanu`.`share`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`share` ;

CREATE TABLE IF NOT EXISTS `keanu`.`share` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shared_source_id` INT NULL COMMENT 'Utm parameters used in the shared URL',
  `conversion_count` INT NOT NULL COMMENT 'Number of people who took action directly thanks this share',
  `new_member_count` INT NOT NULL COMMENT 'Number of people who became members of the organisation directly thanks to this share',
  `share_count` INT NOT NULL COMMENT 'Number of people who did at least one share directly thanks to this share',
  `action_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_share_contact_action1_idx` (`action_id` ASC),
  INDEX `fk_share_source1_idx` (`shared_source_id` ASC),
  CONSTRAINT `fk_share_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_share_source1`
    FOREIGN KEY (`shared_source_id`)
    REFERENCES `keanu`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A share is a type of action: it is the act of referring an action page to other people.\nA share is associated to 2 source records: the one that led to the share action (the action source), and the one that will be the source of any action coming from that share (the shared source).';


-- -----------------------------------------------------
-- Table `keanu`.`open`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`open` ;

CREATE TABLE IF NOT EXISTS `keanu`.`open` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `broadcast_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT 'When the notification of the open was received',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_event_opened') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_open_broadcast_idx` (`broadcast_id` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_open_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_open_broadcast`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_open_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'An open is the act of displaying the content of a broadcast.\nFor mailings, it is typically captured by adding to the broadcast content an image stored in a system that counts requests to that image, which may not capture all actual opens (if the recipient does not display images).';


-- -----------------------------------------------------
-- Table `keanu`.`unsub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`unsub` ;

CREATE TABLE IF NOT EXISTS `keanu`.`unsub` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `broadcast_id` INT NOT NULL COMMENT 'The broadcast from which the contact sent the unsubscribe request',
  `contact_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT 'When te unsubscribe request was received',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_event_unsubscribe') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_unsub_broadcast_idx` (`broadcast_id` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_unsub_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_unsub_broadcast`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unsub_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'An unsub is the request from a broadcast recipient not to receive further broadcasts anymore. \nWhile people may send such a request through different means, an unsub refers specifically to the act of using one of the unsuscribe options that are mandatory in any mass communication.';


-- -----------------------------------------------------
-- Table `keanu`.`broadcast_metric`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`broadcast_metric` ;

CREATE TABLE IF NOT EXISTS `keanu`.`broadcast_metric` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `broadcast_id` INT NOT NULL,
  `broadcast_name` VARCHAR(128) NOT NULL,
  `segment_id` INT NOT NULL,
  `metric` ENUM('recipients', 'opens', 'openers', 'clicks', 'clickers', 'conversions', 'converted', 'activated', 'unsubs', 'bounces', 'spams', 'likely_forwarders', 'openers_rate', 'clickers_rate', 'sharers_rate', 'likely_forwarders_rate', 'sharers', 'shares', 'clickers_to_openers', 'converted_to_clickers', 'bounce_rate', 'spam_rate', 'oneoff_donations', 'oneoff_amount', 'monthly_donations', 'monthly_amount', 'unsub_rate', 'activated_rate') NOT NULL,
  `value` DECIMAL(12,4) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_broadcast_metric_broadcast1_idx` (`broadcast_id` ASC),
  INDEX `fk_broadcast_metric_segment1_idx` (`segment_id` ASC),
  UNIQUE INDEX `broadcast_metric_segment_idx` (`broadcast_id` ASC, `segment_id` ASC, `metric` ASC),
  CONSTRAINT `fk_broadcast_metrics_broadcast1`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_broadcast_metrics_segment1`
    FOREIGN KEY (`segment_id`)
    REFERENCES `keanu`.`segment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A broadcast metric is an indicator of how recipients interacted with the broadcast. In this table, the value of each metric is given for a specific contact segment (which may be the \"everyone\" segment).';


-- -----------------------------------------------------
-- Table `keanu`.`consent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`consent` ;

CREATE TABLE IF NOT EXISTS `keanu`.`consent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT 'When the consent event happened',
  `status` ENUM('accepted', 'rejected', 'pending', 'cancelled') NOT NULL COMMENT 'One of:\n - accepted: the person became a member\n - rejected: the person refused to become a member\n - pending: the person was asked asynchronously (eg by email) to become a member\n - cancelled: the person withdrew their consent',
  `trigger_action_id` INT NULL COMMENT 'The action that led to this consent event',
  `campaign_id` INT NULL,
  `source_id` INT NULL COMMENT 'The utm parameters that led to this consent.',
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_activity') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_share_contact_action1_idx` (`trigger_action_id` ASC),
  INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_consent_campaign1_idx` (`campaign_id` ASC),
  INDEX `fk_consent_source1_idx` (`source_id` ASC),
  INDEX `fk_consent_contact1_idx` (`contact_id` ASC),
  INDEX `status_idx` (`status` ASC),
  CONSTRAINT `fk_share_action10`
    FOREIGN KEY (`trigger_action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consent_campaign1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `keanu`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consent_source1`
    FOREIGN KEY (`source_id`)
    REFERENCES `keanu`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consent_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'In this database, a consent is either any event regarding a person\'s explicit consent to have their personal data processed or used for a certain purpose.\nIt may be an asynchronous consent ask, an asynchronous consent response, a synchronous consent ask and response, or an unsollicited consent cancellation.';


-- -----------------------------------------------------
-- Table `keanu`.`campaign_metric`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`campaign_metric` ;

CREATE TABLE IF NOT EXISTS `keanu`.`campaign_metric` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campaign_id` INT NOT NULL,
  `segment_id` INT NOT NULL,
  `metric` ENUM('recipients', 'messages', 'unsubs', 'actions', 'new_members', 'activated', 'shares', 'donations', 'donations_total_amount') NOT NULL COMMENT 'One of the following:\n - recipients: number of broadcast recipients targeted by the campaign\n - messages: total number of broadcast messages (emails, sms, etc) sent for the campaign\n - unsubs: number of people who unsubscribed through a broadcast of the campaign\n - actions: total number of actions of any type attributed to the campaign\n - new_members: total number of people who subscribed to the organisation mailing list thanks to the campaign\n - activated: number of people who joined the active members\'segment via an action linked to the campaign\n - shares: number of actions of type share associated to the campaign\n - donations_total_amount: total amount of money (one-off and recurring total) fundraised via the campaign',
  `value` DECIMAL(12,4) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_campaign_metric_campaign1_idx` (`campaign_id` ASC),
  INDEX `fk_campaign_metric_segment1_idx` (`segment_id` ASC),
  UNIQUE INDEX `campaign_segment_metric_idx` (`campaign_id` ASC, `segment_id` ASC, `metric` ASC),
  CONSTRAINT `fk_campaign_metric_campaign1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `keanu`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaign_metric_segment1`
    FOREIGN KEY (`segment_id`)
    REFERENCES `keanu`.`segment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'A campaign metric is a indicator of how people interacted with the campaign. In this table, the value of each metric is given for a specific contact segment (which may be the \"everyone\" segment).';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
