-- MySQL Script generated by MySQL Workbench
-- Tue 17 Mar 2020 16:14:22 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema keanu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema keanu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `keanu` ;
USE `keanu` ;

-- -----------------------------------------------------
-- Table `keanu`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`contact` ;

CREATE TABLE IF NOT EXISTS `keanu`.`contact` (
  `id` INT NOT NULL,
  `email_domain` VARCHAR(254) NULL,
  `created_at` DATETIME NOT NULL,
  `postal_code` VARCHAR(10) NULL,
  `country` VARCHAR(64) NULL,
  `preferred_language` VARCHAR(5) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `created_at_idx` (`created_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`campaign` ;

CREATE TABLE IF NOT EXISTS `keanu`.`campaign` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `started_at` DATETIME NOT NULL,
  `ended_at` DATETIME NULL,
  `campaign_type` ENUM('youmove', 'eci', 'wemove') NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_campaign') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC));


-- -----------------------------------------------------
-- Table `keanu`.`topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`topic` ;

CREATE TABLE IF NOT EXISTS `keanu`.`topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `keanu`.`campaign_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`campaign_topic` ;

CREATE TABLE IF NOT EXISTS `keanu`.`campaign_topic` (
  `campaign_id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  INDEX `fk_campaign_topics_campaigns1_idx` (`campaign_id` ASC),
  INDEX `fk_campaign_topics_topics1_idx` (`topic_id` ASC),
  UNIQUE INDEX `campaign_tagged_once` (`topic_id` ASC, `campaign_id` ASC),
  CONSTRAINT `fk_campaign_topics_campaigns1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `keanu`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campaign_topics_topics1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `keanu`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`source` ;

CREATE TABLE IF NOT EXISTS `keanu`.`source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(45) NOT NULL,
  `medium` VARCHAR(45) NOT NULL,
  `campaign` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(2) NULL,
  `description` VARCHAR(64) NULL,
  `action_count` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_codes` (`source` ASC, `medium` ASC, `campaign` ASC))
ENGINE = InnoDB
COMMENT = '+ cache aggregates\n';


-- -----------------------------------------------------
-- Table `keanu`.`action_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`action_page` ;

CREATE TABLE IF NOT EXISTS `keanu`.`action_page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campaign_id` INT NOT NULL,
  `action_type` ENUM('sign', 'email', 'tweet', 'facebook', 'call', 'share', 'donate', 'consent') NOT NULL,
  `language` VARCHAR(5) NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_campaign') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actions_campaigns1_idx` (`campaign_id` ASC),
  UNIQUE INDEX `external_id_system_action_type_idx` (`external_system` ASC, `external_id` ASC, `action_type` ASC),
  INDEX `action_type_idx` (`action_type` ASC),
  CONSTRAINT `fk_actions_campaigns1`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `keanu`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `keanu`.`action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`action` ;

CREATE TABLE IF NOT EXISTS `keanu`.`action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `value` DECIMAL(2) NULL COMMENT 'for each share we have:\n- sign count\n- new members\n- how many shares\n\ndonation:\n- recurring\n- provider\n',
  `source_id` INT NULL,
  `action_page_id` INT NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_contribution_recur', 'civicrm_contribution', 'civicrm_activity') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actions_contacts1_idx` (`contact_id` ASC),
  INDEX `fk_actions_sources1_idx` (`source_id` ASC),
  INDEX `fk_actions_action_pages1_idx` (`action_page_id` ASC),
  INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_contact_actions_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_actions_sources1`
    FOREIGN KEY (`source_id`)
    REFERENCES `keanu`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_actions_action_page1`
    FOREIGN KEY (`action_page_id`)
    REFERENCES `keanu`.`action_page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`tag` ;

CREATE TABLE IF NOT EXISTS `keanu`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `external_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `external_id_idx` (`external_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`contact_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`contact_tag` ;

CREATE TABLE IF NOT EXISTS `keanu`.`contact_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `tag_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `joined` DATETIME NOT NULL,
  `left` DATETIME NOT NULL,
  `trigger_action_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_ct_segments1_idx` (`tag_id` ASC),
  INDEX `fk_id_ct_contacts1_idx` (`contact_id` ASC),
  INDEX `fk_id_ct_contact_actions1_idx` (`trigger_action_id` ASC),
  INDEX `joined_idx` (`joined` ASC),
  INDEX `left_idx` (`left` ASC),
  CONSTRAINT `fk_id_ct_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `keanu`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ct_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ct_contact_action1`
    FOREIGN KEY (`trigger_action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`broadcast_test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`broadcast_test` ;

CREATE TABLE IF NOT EXISTS `keanu`.`broadcast_test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `sent_at` DATETIME NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_abtest') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `sent_at_idx` (`sent_at` ASC))
ENGINE = InnoDB
COMMENT = '+ link to test mailing ? ';


-- -----------------------------------------------------
-- Table `keanu`.`broadcast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`broadcast` ;

CREATE TABLE IF NOT EXISTS `keanu`.`broadcast` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `broadcast_type` ENUM('email', 'fb_ad') NOT NULL,
  `ask_type` ENUM('sign', 'email', 'tweet', 'facebook', 'call', 'share', 'donate', 'noop_read', 'noop_watch') NOT NULL COMMENT 'Should match the actions.action_type !',
  `language` VARCHAR(5) NOT NULL,
  `sent_at` DATETIME NOT NULL,
  `broadcast_test_id` INT NULL,
  `campaign_id` INT NOT NULL DEFAULT 0,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing') NULL,
  PRIMARY KEY (`id`),
  INDEX `broadcast_type_idx` (`broadcast_type` ASC),
  INDEX `ask_type_idx` (`ask_type` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_broadcast_test_idx` (`broadcast_test_id` ASC),
  INDEX `fk_broadcast_campaign_idx` (`campaign_id` ASC),
  CONSTRAINT `fk_broadcast_test`
    FOREIGN KEY (`broadcast_test_id`)
    REFERENCES `keanu`.`broadcast_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_broadcast_campaign`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `keanu`.`campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`broadcast_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`broadcast_link` ;

CREATE TABLE IF NOT EXISTS `keanu`.`broadcast_link` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` TEXT NOT NULL,
  `broadcast_id` INT NOT NULL,
  `source_id` INT NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_trackable_url') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_broadcast_link_broadcast_idx` (`broadcast_id` ASC),
  INDEX `fk_broadcast_link_source_idx` (`source_id` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_broadcast_link_broadcast`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_broadcast_link_source`
    FOREIGN KEY (`source_id`)
    REFERENCES `keanu`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`click`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`click` ;

CREATE TABLE IF NOT EXISTS `keanu`.`click` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `mailing_link_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_event_trackable_url_open') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mailing_links_id1_idx` (`mailing_link_id` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_click_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_mailing_links_id1`
    FOREIGN KEY (`mailing_link_id`)
    REFERENCES `keanu`.`broadcast_link` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_click_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`segmentation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`segmentation` ;

CREATE TABLE IF NOT EXISTS `keanu`.`segmentation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_group', 'civicrm_option_group') NULL,
  PRIMARY KEY (`id`),
  INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`segment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`segment` ;

CREATE TABLE IF NOT EXISTS `keanu`.`segment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `segmentation_id` INT NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_group', 'civicrm_option_value', 'civicrm_country') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_segment_segmentation1_idx` (`segmentation_id` ASC),
  INDEX `external_id_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_segment_segmentation1`
    FOREIGN KEY (`segmentation_id`)
    REFERENCES `keanu`.`segmentation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`contact_segment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`contact_segment` ;

CREATE TABLE IF NOT EXISTS `keanu`.`contact_segment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `segmentation_id` INT NOT NULL COMMENT 'this is necessary to have one segment per segmentation enforced for a contact.',
  `segment_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `joined_at` DATETIME NOT NULL,
  `left_at` DATETIME NULL,
  `trigger_action_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_segment_map_contact_segment1_idx` (`segmentation_id` ASC),
  INDEX `fk_contact_segment_map_contacts1_idx` (`contact_id` ASC),
  INDEX `fk_contact_segment_map_contact_action1_idx` (`trigger_action_id` ASC),
  INDEX `fk_contact_segmentation_segment1_idx` (`segment_id` ASC),
  UNIQUE INDEX `one_segment_in_segmentation_at_a_time` (`segmentation_id` ASC, `segment_id` ASC, `contact_id` ASC, `joined_at` ASC),
  INDEX `joined_at_idx` (`joined_at` ASC),
  INDEX `left_at_idx` (`left_at` ASC),
  CONSTRAINT `fk_contact_segment_map_contact_segment1`
    FOREIGN KEY (`segmentation_id`)
    REFERENCES `keanu`.`segmentation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_segment_map_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_segment_map_contact_action1`
    FOREIGN KEY (`trigger_action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_segmentation_segment1`
    FOREIGN KEY (`segment_id`)
    REFERENCES `keanu`.`segment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`donation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`donation` ;

CREATE TABLE IF NOT EXISTS `keanu`.`donation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_id` INT NOT NULL,
  `frequency_unit` ENUM('one-off', 'month') NOT NULL,
  `frequency_interval` SMALLINT NOT NULL DEFAULT 1,
  `amount` DECIMAL(10,2) NOT NULL,
  `original_currency` VARCHAR(3) NOT NULL,
  `original_amount` DECIMAL(16,2) NOT NULL,
  `payment_method` ENUM('sepa', 'paypal', 'card', 'bank_transfer') NOT NULL,
  `started_at` DATETIME NOT NULL,
  `ended_at` DATETIME NULL,
  `total_amount` DECIMAL(16,2) NOT NULL,
  `payment_count` INT NOT NULL DEFAULT 0,
  `fail_count` INT NOT NULL DEFAULT 0,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_contribution_recur', 'civicrm_contribution') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_donation_contact_action1_idx` (`action_id` ASC),
  UNIQUE INDEX `external_id_external_system_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_donation_action10`
    FOREIGN KEY (`action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`payment` ;

CREATE TABLE IF NOT EXISTS `keanu`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `donation_id` INT NOT NULL,
  `receive_date` DATETIME NOT NULL,
  `status` ENUM('success', 'fail', 'cancel') NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_contribution_recur', 'civicrm_contribution') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_donation1_idx` (`donation_id` ASC),
  UNIQUE INDEX `external_id_external_system_idx` (`external_system` ASC, `external_id` ASC),
  CONSTRAINT `fk_payment_donation1`
    FOREIGN KEY (`donation_id`)
    REFERENCES `keanu`.`donation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`share`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`share` ;

CREATE TABLE IF NOT EXISTS `keanu`.`share` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shared_source_id` INT NULL,
  `conversion_count` INT NOT NULL,
  `new_member_count` INT NOT NULL,
  `share_count` INT NOT NULL,
  `action_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_share_contact_action1_idx` (`action_id` ASC),
  INDEX `fk_share_source1_idx` (`shared_source_id` ASC),
  CONSTRAINT `fk_share_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_share_source1`
    FOREIGN KEY (`shared_source_id`)
    REFERENCES `keanu`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`conversion_count`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`conversion_count` ;

CREATE TABLE IF NOT EXISTS `keanu`.`conversion_count` (
  `contact_id` INT NOT NULL,
  `conversion_type` VARCHAR(32) NOT NULL,
  `conversions` INT NOT NULL DEFAULT 0,
  `impressions` INT NULL DEFAULT NULL COMMENT 'impressions = NULL means we do not have this data\n',
  PRIMARY KEY (`contact_id`, `conversion_type`),
  INDEX `fk_conversion_count_contact1_idx` (`contact_id` ASC),
  UNIQUE INDEX `unique_combined_key` (`conversion_type` ASC, `contact_id` ASC),
  CONSTRAINT `fk_conversion_count_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`conversion_benchmark`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`conversion_benchmark` ;

CREATE TABLE IF NOT EXISTS `keanu`.`conversion_benchmark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conversion_type` VARCHAR(32) NOT NULL,
  `segment_id` INT NULL DEFAULT NULL,
  `broadcast_id` INT NULL DEFAULT NULL COMMENT 'is this needed? the benchmarks should be for segments and tags... would we want to calculate a benchmark for particular broadcast ??',
  `tag_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `rate` DECIMAL(4,4) NOT NULL,
  `quantile_low` DECIMAL(4,4) NULL,
  `quantile_high` DECIMAL(4,4) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conversion_rate_segment1_idx` (`segment_id` ASC),
  INDEX `fk_conversion_rate_broadcast1_idx` (`broadcast_id` ASC),
  INDEX `fk_conversion_rate_tag1_idx` (`tag_id` ASC),
  INDEX `conversion_type_idx` (`conversion_type` ASC),
  CONSTRAINT `fk_conversion_rate_segment1`
    FOREIGN KEY (`segment_id`)
    REFERENCES `keanu`.`segment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversion_rate_broadcast1`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversion_rate_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `keanu`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`conversion_rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`conversion_rate` ;

CREATE TABLE IF NOT EXISTS `keanu`.`conversion_rate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conversion_type` VARCHAR(32) NOT NULL,
  `segment_id` INT NULL DEFAULT NULL,
  `broadcast_id` INT NOT NULL,
  `tag_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `rate` DECIMAL(4,4) NOT NULL,
  `quantile_low` DECIMAL(4,4) NULL,
  `quantile_high` DECIMAL(4,4) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conversion_rate_segment1_idx` (`segment_id` ASC),
  INDEX `fk_conversion_rate_broadcast1_idx` (`broadcast_id` ASC),
  INDEX `fk_conversion_rate_tag1_idx` (`tag_id` ASC),
  INDEX `conversion_type_idx` (`conversion_type` ASC),
  CONSTRAINT `fk_conversion_rate_segment10`
    FOREIGN KEY (`segment_id`)
    REFERENCES `keanu`.`segment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversion_rate_broadcast10`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversion_rate_tag10`
    FOREIGN KEY (`tag_id`)
    REFERENCES `keanu`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`open`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`open` ;

CREATE TABLE IF NOT EXISTS `keanu`.`open` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `broadcast_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_event_opened') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_open_broadcast_idx` (`broadcast_id` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_open_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_open_broadcast`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_open_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`unsub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`unsub` ;

CREATE TABLE IF NOT EXISTS `keanu`.`unsub` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `broadcast_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `external_id` INT NULL,
  `external_system` ENUM('civicrm_mailing_event_unsubscribe') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_unsub_broadcast_idx` (`broadcast_id` ASC),
  UNIQUE INDEX `external_system_id_idx` (`external_system` ASC, `external_id` ASC),
  INDEX `fk_unsub_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_unsub_broadcast`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unsub_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `keanu`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`broadcast_metric`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`broadcast_metric` ;

CREATE TABLE IF NOT EXISTS `keanu`.`broadcast_metric` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `broadcast_id` INT NOT NULL,
  `broadcast_name` VARCHAR(128) NOT NULL,
  `segment_id` INT NOT NULL,
  `metric` ENUM('recipients', 'opens', 'openers', 'clicks', 'clickers', 'conversions', 'converted', 'activated', 'unsubs', 'bounces', 'spams', 'likely_forwarders', 'openers_rate', 'clickers_rate', 'sharers_rate', 'likely_forwarders_rate', 'sharers', 'shares', 'clickers_to_openers', 'converted_to_clickers', 'bounce_rate', 'spam_rate') NOT NULL,
  `value` DECIMAL(12,4) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_broadcast_metric_broadcast1_idx` (`broadcast_id` ASC),
  INDEX `fk_broadcast_metric_segment1_idx` (`segment_id` ASC),
  UNIQUE INDEX `broadcast_metric_segment_idx` (`broadcast_id` ASC, `segment_id` ASC, `metric` ASC),
  CONSTRAINT `fk_broadcast_metrics_broadcast1`
    FOREIGN KEY (`broadcast_id`)
    REFERENCES `keanu`.`broadcast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_broadcast_metrics_segment1`
    FOREIGN KEY (`segment_id`)
    REFERENCES `keanu`.`segment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keanu`.`consent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keanu`.`consent` ;

CREATE TABLE IF NOT EXISTS `keanu`.`consent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('accepted', 'rejected', 'pending') NOT NULL,
  `action_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_share_contact_action1_idx` (`action_id` ASC),
  CONSTRAINT `fk_share_action10`
    FOREIGN KEY (`action_id`)
    REFERENCES `keanu`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
